services:
  - type: web
    name: healthchecks-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hc.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: SECRET_KEY
        value: sua_chave_secreta
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DEBUG
        value: "False"
      - key: SITE_ROOT
        value: https://your-app-name.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: healthchecks-db
          property: connectionString
databases:
  - name: healthchecks-db
    plan: free
    postgresMajorVersion: 15
